sudo: false
dist: trusty
language: generic

addons:
  apt:
    sources:
    - hvr-ghc
    - ubuntu-toolchain-r-test
    packages:
    - cabal-install-2.2
    - ghc-8.2.2
    - alex-3.1.4
    - happy-1.19.5
    - gcc-6

cache:
  bundler: false
  directories:
  - $HOME/.ghc/
  - $HOME/.ghcjs/
  - $HOME/.cabal/bin
  - $HOME/.cabal/share
  - $HOME/.cabal/lib
  - $HOME/.cabal/libexec

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - export PATH=/opt/cabal/2.2/bin:$PATH
    - export PATH=/opt/alex/3.1.4/bin:$PATH
    - export PATH=/opt/happy/1.19.5/bin:$PATH
    - export PATH=/opt/ghc/bin:$PATH
    - export PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
    - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/share
    - cabal update

jobs:
 include:
   - stage: install ghcjs dependencies
     install:
      - cd ..; pwd
      - test -e $HOME/.cabal/bin/HsColour || cabal install hscolour
      - test -e $HOME/.cabal/bin/hsc2hs || cabal install hsc2hs
      - test -e $HOME/.cabal/bin/ghcjs || git clone --recursive https://github.com/ghcjs/ghcjs.git -b ghc-8.2 ghcjs-8.2
      - test -e $HOME/.cabal/bin/ghcjs || cd ghcjs-8.2
      - test -e $HOME/.cabal/bin/ghcjs || sed -i -e s,--exclude-vcs-ignores,, ./utils/updateBootArchive.sh
      - test -e $HOME/.cabal/bin/ghcjs || ./utils/makePackages.sh
      - test -e $HOME/.cabal/bin/ghcjs || cabal install -j1 --dependencies-only
                 ./
                 ./lib/ghc-api-ghcjs/
                 ./lib/ghci-ghcjs/
                 ./lib/ghcjs-th/
                 ./lib/haddock-api-ghcjs/
                 ./lib/haddock-library-ghcjs/
                 ./lib/template-haskell-ghcjs/
     script:
      - ghc-pkg list

   - stage: install ghcjs
     install:
      - cd ..; pwd
      - test -e $HOME/.cabal/bin/HsColour || cabal install hscolour
      - test -e $HOME/.cabal/bin/hsc2hs || cabal install hsc2hs
      - test -e $HOME/.cabal/bin/ghcjs || git clone --recursive https://github.com/ghcjs/ghcjs.git -b ghc-8.2 ghcjs-8.2
      - test -e $HOME/.cabal/bin/ghcjs ||  cd ghcjs-8.2
      - test -e $HOME/.cabal/bin/ghcjs || sed -i -e s,--exclude-vcs-ignores,, ./utils/updateBootArchive.sh
      - test -e $HOME/.cabal/bin/ghcjs || ./utils/makePackages.sh
      - test -e $HOME/.cabal/bin/ghcjs || cabal install -j1 --ghc-option=+RTS --ghc-option=-M2G --ghc-option=-RTS
                 ./
                 ./lib/ghc-api-ghcjs/
                 ./lib/ghci-ghcjs/
                 ./lib/ghcjs-th/
                 ./lib/haddock-api-ghcjs/
                 ./lib/haddock-library-ghcjs/
                 ./lib/template-haskell-ghcjs/
     script:
      - ghcjs --version
      - ghcjs-boot --version

   - stage: boot ghcjs
     install:
      - cd ..; pwd
      - ln -sf /usr/bin/gcc-6 $HOME/.cabal/bin/gcc
      - test -e $HOME/.ghcjs/*/ghcjs/ghcjs_boot.completed || ghcjs-boot --no-haddock --no-prof
     script:
       - ghcjs-pkg list

   # needed due to https://github.com/ghcjs/ghcjs-base/issues/81
   - stage: install ghcjs-base (ghcjs)
     install:
       - cabal --version
       - 'ghcjs-pkg list ghcjs-base | grep -q ghcjs-base ||
         { git clone https://github.com/ghcjs/ghcjs-base &&
           cabal install -j1 --ghcjs --constraint="primitive < 0.6.4.0" ./ghcjs-base;
         }'
     script:
       - ghcjs-pkg list

   - stage: install program dependencies (ghcjs)
     install:
       - cabal --version
       - cabal install -j1 --ghcjs --dependencies-only --disable-tests --constraint="primitive < 0.6.4.0"
     script:
       - ghcjs-pkg list

   - stage: build, test and deploy
     script:
       - cabal configure --distdir=dist-ghcjs --ghcjs --disable-library-profiling
       - cabal build     --distdir=dist-ghcjs
       - cabal haddock   --distdir=dist-ghcjs --executables --internal --hyperlink-source
       - cp -vr dist-ghcjs/build/*/*.jsexe gh-page
       - cp -vr dist-ghcjs/doc/html/*/* gh-page/doc
       # - echo 'domain.de' > gh-page/CNAME

     deploy:
       provider: pages
       local-dir: gh-page
       # fqdn: domain.de
       keep-history: true
       allow-empty-commit: true
       skip-cleanup: true
       github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
       on:
         branch: master

before_cache:
  - rm -rf $HOME/.ghcjs/*/ghcjs/ghcjs-boot/
  - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/share

